name: conda-test1
channels:
  - conda-forge
dependencies:
  - dask
  - toolz
  - python=3.6
  - coverage=4.4.1
  - matplotlib=2.0.2
  - numpy=1.13.1
  - pytest=3.1.3
  - pytest-cov=2.3.1
  - scikit-learn=0.18.2
  - scipy=0.19.1
  - sfepy=2018.2
  - notebook
  - dask-ml
  - nbval
