# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Create env and install dependencies
          command: |
            conda env create -f environment.yml
            source activate conda-test1
      - run:
          name: Activate env
          command: |
            source activate conda-test1
      # Step 3: run linter and tests
      - run:
          name: Install Pymks
          command: |
            python setup.py install
            python -c "import pymks;pymks.test()"
      - run:
          name: run tests
          command: |
            source activate conda-test1
            python -c "import pymks;pymks.test()"
      - run:
          name: run tests
          command: |
            source activate conda-test1
            py.test
